apiVersion: v1
kind: Service
metadata:
  name: spring-crud-service
spec:
  selector:
    app: spring-crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Mapping the service to the container port
  type: LoadBalancer  # Exposes the service externally
